name: Laravel - build and push on new Release or Modif

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"
    paths:
      - laravel/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Docker meta migrator
        id: meta_migrator
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/serotonie/ovms-admin_migrator          
            serotonie/ovms-admin_migrator          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw, latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker meta scheduler
        id: meta_scheduler
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/serotonie/ovms-admin_scheduler          
            serotonie/ovms-admin_scheduler          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw, latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker meta queue-worker
        id: meta_queue-worker
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/serotonie/ovms-admin_queue-worker          
            serotonie/ovms-admin_queue-worker          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw, latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker meta frontend
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/serotonie/ovms-admin_frontend          
            serotonie/ovms-admin_frontend          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw, latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push migrator
        uses: docker/build-push-action@v6
        with:
          context: laravel
          target: migrator
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_migrator.outputs.tags }}
          labels: ${{ steps.meta_migrator.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta_migrator.outputs.tags }}
          cache-to: type=inline
      - name: Update repo description migrator
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: serotonie/ovms-admin_migrator
      - name: Build and push scheduler
        uses: docker/build-push-action@v6
        with:
          context: laravel
          target: scheduler
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_scheduler.outputs.tags }}
          labels: ${{ steps.meta_scheduler.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta_scheduler.outputs.tags }}
          cache-to: type=inline
      - name: Update repo description scheduler
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: serotonie/ovms-admin_scheduler
      - name: Build and push queue-worker
        uses: docker/build-push-action@v6
        with:
          context: laravel
          target: queue-worker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_queue-worker.outputs.tags }}
          labels: ${{ steps.meta_queue-worker.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta_queue-worker.outputs.tags }}
          cache-to: type=inline
      - name: Update repo description queue-worker
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: serotonie/ovms-admin_queue-worker
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: laravel
          target: frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta_frontend.outputs.tags }}
          cache-to: type=inline
      - name: Update repo description frontend
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: serotonie/ovms-admin_frontend
