name: Mosquitto - build and push on new Release or Modif

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"
    paths:
      - mosquitto/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Docker meta mosquitto
        id: meta_mosquitto
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/serotonie/ovms-admin_mosquitto          
            serotonie/ovms-admin_mosquitto          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw, latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mosquitto-go-auth
        uses: docker/build-push-action@v6
        with:
          context: mosquitto/mosquitto-go-auth
          platforms: linux/amd64,linux/arm64    
          build-args: |
            LWS_VERSION=4.3.5
            MOSQUITTO_VERSION=2.0.22
          tags: serotonie/mosquitto-go-auth:latest
          push: true
          cache-from: type=registry,ref=serotonie/mosquitto-go-auth:latest
          cache-to: type=inline

      - name: Build and push mosquitto
        uses: docker/build-push-action@v6
        with:
          context: mosquitto
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_mosquitto.outputs.tags }}
          labels: ${{ steps.meta_mosquitto.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta_mosquitto.outputs.tags }}
          cache-to: type=inline
      - name: Update repo description mosquitto
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: serotonie/ovms-admin_mosquitto
